# Generated by Django 5.1.5 on 2025-01-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareHomes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('care_home_name', models.CharField(default='', max_length=255)),
                ('address_line_1', models.CharField(default='', max_length=200)),
                ('address_line_2', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('city_town', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('county', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('post_code', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('phone_number', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('registration_number', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
    ]
