# Generated by Django 5.1.5 on 2025-01-24 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BrightCare_CareHomes', '0001_initial'),
        ('BrightCare_staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carehomes',
            name='manager',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manages_home', to='BrightCare_staff.staffprofile'),
        ),
        migrations.AddField(
            model_name='carehomes',
            name='staff',
            field=models.ManyToManyField(blank=True, related_name='care_homes', to='BrightCare_staff.staffprofile'),
        ),
    ]
