# Generated by Django 5.1.5 on 2025-01-24 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BrightCare_CareHomes', '0002_initial'),
        ('BrightCare_YoungPerson', '0001_initial'),
        ('BrightCare_staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_of_incident', models.CharField(blank=True, help_text='Where did the incident take place', max_length=300, null=True)),
                ('incident_title', models.CharField(default='', max_length=100)),
                ('description', models.TextField(help_text='Please explain what happened.', max_length=5000)),
                ('date_occurred', models.DateTimeField()),
                ('date_reported', models.DateTimeField()),
                ('care_home', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='BrightCare_CareHomes.carehomes')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to='BrightCare_staff.staffprofile')),
                ('young_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='BrightCare_YoungPerson.youngperson')),
            ],
        ),
    ]
