# Generated by Django 5.1.5 on 2025-01-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAssesment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likelihood_score', models.IntegerField(default=0)),
                ('impact_score', models.IntegerField(default=0)),
                ('overall_sccore', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, default='', max_length=2000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RiskFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_title', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
            ],
        ),
    ]
