# Generated by Django 5.1.5 on 2025-01-24 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BrightCare_Assessments', '0001_initial'),
        ('BrightCare_YoungPerson', '0001_initial'),
        ('BrightCare_staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskassesment',
            name='assessed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='BrightCare_staff.staffprofile'),
        ),
        migrations.AddField(
            model_name='riskassesment',
            name='young_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='BrightCare_YoungPerson.youngperson'),
        ),
        migrations.AddField(
            model_name='riskassesment',
            name='risk_factors',
            field=models.ManyToManyField(blank=True, related_name='assessments', to='BrightCare_Assessments.riskfactor'),
        ),
    ]
