# Generated by Django 5.1.5 on 2025-01-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrightCare_YoungPerson', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youngperson',
            name='guardians',
            field=models.ManyToManyField(blank=True, related_name='young_people', to='BrightCare_YoungPerson.guardian'),
        ),
    ]
